apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Multicluster
spec:
  destination:
    name: ''
    namespace: ntnx-test-1
    server: 'https://10.42.49.45:443'
  source:
    path: nutanix-microservice
    repoURL: 'https://github.com/rajeevramani/multicluster-app-demo.git'
    targetRevision: HEAD
    directory:
      recurse: false
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
