apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-microservice
  namespace: argocd
spec:
  project: default
  source:
    path: azure-service
    repoURL: "https://github.com/rajeevramani/multicluster-app-demo.git"
    targetRevision: HEAD
    
  destination:
    namespace: ntnx-test-1
    server: "https://rrazuredev-azuredevops-f3ce23-420ed21e.hcp.eastus.azmk8s.io:443"
  
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
