apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-microservice
  namespace: argocd
spec:
  project: default
  source:
    path: frontend
    repoURL: 'https://github.com/rajeevramani/multicluster-app-demo.git'
    targetRevision: HEAD

  destination:
    namespace: ntnx-test-1
    server: 'https://10.42.49.45:443'
  
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
