apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutanixmicroservice
  namespace: ntnx-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nutanixmicroservice
  template:
    metadata:
      labels:
        app: nutanixmicroservice
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: nutanixmicroservice
          image: rajeevramani/nutanix-api:v1
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
      # imagePullSecrets:
      #   - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: nutanixmicroservice
  namespace: ntnx-test-1
spec:
  ports:
    - port: 80
  selector:
    app: nutanixmicroservice
