apiVersion: v1
kind: Namespace
metadata:
  name: ntnx-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azuremicroservice
  namespace: ntnx-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azuremicroservice
  template:
    metadata:
      labels:
        app: azuremicroservice
      annotations:
        linkerd.io/inject: enabled
        mirror.linkerd.io/exported: "true"
    spec:
      containers:
        - name: azuremicroservice
          image: rajeevramani/azure-api:v1
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "20m"
          ports:
            - containerPort: 80
      # imagePullSecrets:
      #   - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: azuremicroservice
  namespace: ntnx-test-1
spec:
  ports:
    - port: 80
  selector:
    app: azuremicroservice
